import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ApolloWrapper } from "./ApolloWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>regenerOntology</title>
      </head>
      <body className={`${inter.className}`}>
        <div className="min-h-screen flex flex-col lg:mx-20 mx-10 bg-white">
          <header className="py-4 px-24 flex">
            <h1 className="text-2xl">regenerOntology</h1>
          </header>
          <main className=" flex-grow flex-col items-center justify-between p-24 flex-0 ">
            <ApolloWrapper>{children}</ApolloWrapper>
          </main>
        </div>
      </body>
    </html>
  );
}
